Refactor code to integrate logger and terminal display package

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -12,14 +12,18 @@ jobs:
         run: echo "Job 1 - Step 1"
       - name: Step 2
         run: echo "Job 1 - Step 2"
+
   job2:
     runs-on: ubuntu-latest
     needs: job1
     steps:
       - name: Step 1
         run: echo "Job 2 - Step 1 (runs after Job 1)"
-      - name: Step 2
-        run: echo "Job 2 - Step 2"
+      - name: Step 2 (Simulate Error)
+        run: |
+          echo "Job 2 - Step 2 will now fail..."
+          exit 1   # <-- manual error here
+
   job3:
     runs-on: ubuntu-latest
     needs: [job1, job2]
